### PR TITLE
File_Pdf: Fix atoi (CodeGuard)

### LINKED ISSUE #987: CodeGuard - pdf - Access overrun
Incredible 3D Stereograms - Eye Tricks - You Won't Believe Your Eyes! (2007).pdf
File https://cloud.mail.ru/public/BT7Z/xnVK6pnmX

default

Access overrun in process: PreRelease.exe(7152)  - ..\..\..\Source\MediaInfo\Text\File_Pdf.cpp#263
  Attempt to access 262112 byte(s) at 0x059AFFE1, that is at offset 33 in heap block 0x059AFFC0 which is only 262144 bytes long.
  0x00EACFE4 Call to atoi(0x059AFFE1 ["0000000015 00000 n\r\n0000000286 00000 n\r\n0000000367 00000 n\r\n0000000438 00000 n\r\n0000000578 00000 n\r\n0000003864 00000 n\r\n0000004000 00000 n\r\n0000004137 00000 n\r\n0000004245 00000 n\r\n0000004344 00000 n\r\n0000004430 00000 n\r\n0000005755 00000 n\r\n0000005870 00000 n\r\n0000006007 00000 n\r\n0000006144 00000 n\r\n0000006281 00000 n\r\n0000006418 00000 n\r\n0000006555 00000 n\r\n0000006697 00000 n\r\n0000006844 00000 n\r\n0000006991 00000 n\r\n0000007138 00000 n\r\n0000007285 00000 n\r\n0000007432 00000 n\r\n0000007579 00000 n\r\n0000007726 00000 n\r\n0000007873 00000 n\r\n0000008020 00000 n\r\n0000008167 00000 n\r\n0000008314 00000 n\r\n0000008461 00000 n\r\n0000008608 00000 n\r\n0000008755 00000 n\r\n0000008902 00000 n\r\n0000009049 00000 n\r\n0000009196 00000 n\r\n0000009343 00000 n\r\n0000009481 00000 n\r\n0000009624 00000 n\r\n0000009767 00000 n\r\n0000009910 00000 n\r\n0000010053 00000 n\r\n0000010196 00000 n\r\n0000010339 00000 n\r\n0000010482 00000 n\r\n0000010625 00000 n\r\n000001076...])
    0x00B30E21 - ..\..\..\Source\MediaInfo\Text\File_Pdf.cpp#263
    0x00B2FF72 - ..\..\..\Source\MediaInfo\Text\File_Pdf.cpp#122
    0x00559A10 - ..\..\..\Source\MediaInfo\File__Analyze.cpp#1064
    0x00555EA1 - ..\..\..\Source\MediaInfo\File__Analyze.cpp#693
    0x006FC528 - ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1337
    0x00ACE398 - ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#756
    0x00ACC852 - ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#292
    0x006D8964 - ..\..\..\Source\MediaInfo\MediaInfo_File.cpp#1052
    0x00ACBF0D - ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#209
    0x006FAAB4 - ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1083
    0x006F55AE - ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#839
    0x0067A581 - ..\..\..\Source\MediaInfo\MediaInfo.cpp#89
    0x00BEC78B - ..\..\..\Source\PreRelease\VCL\PreRelease_.cpp#45
    0x00BECCBE - C:\git\MediaInfoLib\Source\PreRelease\VCL\PreRelease_.cpp#73
    0x00D896ED
  The object array (0x059AFFC0) [size: 262144 bytes] was created with new[]
    0x005559F9 - ..\..\..\Source\MediaInfo\File__Analyze.cpp#651
    0x006FC528 - ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1337
    0x00ACE398 - ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#756
    0x00ACC852 - ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#292
    0x006D8964 - ..\..\..\Source\MediaInfo\MediaInfo_File.cpp#1052
    0x00ACBF0D - ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#209
    0x006FAAB4 - ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1083
    0x006F55AE - ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#839
    0x0067A581 - ..\..\..\Source\MediaInfo\MediaInfo.cpp#89
    0x00BEC78B - ..\..\..\Source\PreRelease\VCL\PreRelease_.cpp#45
    0x00BECCBE - C:\git\MediaInfoLib\Source\PreRelease\VCL\PreRelease_.cpp#73

### PR DESCRIPTION
**Pull request by pavel-pimenov**
fix #987

### CODE REVIEW

File: Source/MediaInfo/Text/File_Pdf.cpp [hunk 1]
```diff
@@ -260,7 +260,10 @@ void File_Pdf::xref()
         {
             if (*Buffer_Temp=='n')
             {
-                int32u Offset=(int32u)atoi((const char*)(Buffer_Temp-17));
+                char atoi_buf[30];
```
Comment (JeromeMartinez) [inline Source/MediaInfo/Text/File_Pdf.cpp]: 30 --> 18 please (else there is a risk to go beyond the buffer size during copy), and maximal 17 bytes expected for the number.

BTW, as I was also working on it, on my side I added too:
            if (Buffer_Temp+20>=Buffer+Buffer_Size)
                break; //Problem
before  if (*Buffer_Temp=='n')
please add theses lines so only 1 PR for this issue.

File: Source/MediaInfo/Text/File_Pdf.cpp [hunk 2]
```diff
@@ -260,7 +260,10 @@ void File_Pdf::xref()
         {
             if (*Buffer_Temp=='n')
             {
-                int32u Offset=(int32u)atoi((const char*)(Buffer_Temp-17));
+                char atoi_buf[30];
+                atoi_buf[29]=0;
+                strncpy(atoi_buf,Buffer_Temp-17,29);
```
Comment (JeromeMartinez) [inline Source/MediaInfo/Text/File_Pdf.cpp]: memcpy instead.
